import { addDoc, collection, collectionGroup, deleteDoc, doc, getDoc, getDocs, increment, orderBy, query, setDoc, updateDoc, where } from "firebase/firestore"
import { firestore } from "../../firebase"
import { Message } from "../Components/Message/MessageBox"
import { AttendeeModal, AttendeeModalConverter } from "../Modal/AttendeeModal"
import { QRCodeModal, QRCodeModalConverter, QRCodeModalDefault } from "../Modal/QRCodeModal"

export interface ICreateQrCode {
  message: Message,
  docID: string
}

export const createQrCode = async (qrCodeDetails: QRCodeModal): Promise<ICreateQrCode> => {
  return await addDoc(collection(firestore, "qrcode").withConverter(QRCodeModalConverter), qrCodeDetails)
    .then((docRef): ICreateQrCode => {
      console.log("Qrcode document written successfully.")

      const docId = docRef.id;
      const result: ICreateQrCode = {
        message: (new Message(2, "QRCode Generated successfully")),
        docID: docId
      };

      return result;
    })
    .catch((): ICreateQrCode => {
      console.log("Qrcode document not written.");

      const result: ICreateQrCode = {
        message: (new Message(0, "QRCode Generated successfully")),
        docID: "Not Avaliable"
      };

      return result;
    })
}

////
// Mark student present or absent and return message
export const markStudent = async (docRef: string, attendeeModal: AttendeeModal): Promise<Message> => {
  const barcodeRef = doc(firestore, "attendance", docRef);
  const userAttandanceRef = doc(barcodeRef, "students", attendeeModal.uid).withConverter(AttendeeModalConverter);

  return await setDoc(userAttandanceRef, attendeeModal)
    .then(async () => {
      return await setDoc(barcodeRef, { numberOfReads: increment(1) }, { merge: true })
        .then(() => {
          if (attendeeModal.status === 2) return new Message(2, "Marked present successfully")
          else return new Message(2, "Marked absent successfully")
        })
        .catch((error) => {
          console.log("Error Incrementing value", error)
          return new Message(0, "Something went wrong.")
        })
    })
    .catch(() => {
      return new Message(0, "Something went wrong.")
    })
}

export const getStudentsWithDocRef = async (docRef: string): Promise<AttendeeModal[]> => {
  const userattendanceref = collection(firestore, `attendance/${docRef}/students`).withConverter(AttendeeModalConverter)

  const q = query(userattendanceref, orderBy('stamp'))
  const documents = await getDocs(q);

  const result: AttendeeModal[] = [];
  documents.forEach(doc => result.push(doc.data()))

  return result;
}
// ----------------------------------------------------------------------------------------

////
// Return all the barcode generated by the user
export const getBarcodesByUser = async (uid: string): Promise<string[]> => {

  const q = query(collection(firestore, "qrcode"), where("uid", "==", uid), orderBy('timestamp'));
  const document = await getDocs(q)

  const result: string[] = [];
  document.forEach(item => result.push(item.id))
  return result;
}
// -----------------------------------------------------------------------------------------

////
// all the meeting user has given attendance
export const getUserAttendance = async (uid: string): Promise<AttendeeModal[]> => {
  let result: AttendeeModal[] = [];

  const attendanceRef = collectionGroup(firestore, "students").withConverter(AttendeeModalConverter);
  const q = query(attendanceRef, where("uid", "==", uid));

  const querySnapshot = await getDocs(q)
  querySnapshot.forEach(doc => result.push(doc.data()))

  return result
}
// --------------------------------------------------------------------------------------------

////
// Get Barcode data
export const getBarcodeData = async (docRef: string): Promise<QRCodeModal | undefined> => {
  const qrcodeRef = doc(firestore, `qrcode/${docRef}`).withConverter(QRCodeModalConverter);

  const querySnapshot = await getDoc(qrcodeRef);
  return querySnapshot.data();
}
// --------------------------------------------------------------------------------------------

////
// Destroy QRCode
export const destroyQRCode = async (docRef: string): Promise<Message> => {
  const qrcodeRef = doc(firestore, "qrcode", docRef);
  await updateDoc(qrcodeRef, {
    destroyed: true
  })
  return new Message(0, "Barcode destoryed");
}
// --------------------------------------------------------------------------------------------

////
export interface IBarcodeExist {
  data: QRCodeModal;
  message: Message;
}
// Barcode document exist
export const barcodeExist = async (docRef: string): Promise<IBarcodeExist> => {
  const document = await getDoc(doc(firestore, `qrcode/${docRef}`).withConverter(QRCodeModalConverter));

  if (document.exists()) {
    const data = document.data();
    if (data.destroyed)
      return {
        data: data,
        message: (new Message(0, "Invalid Qr Code"))
      }
    return {
      data: data,
      message: (new Message(2, "Valid Qr Code"))
    };
  }
  return {
    data: QRCodeModalDefault,
    message: (new Message(0, "Invalid Qr Code"))
  }
}
// --------------------------------------------------------------------------------------------

////
// Delete User attendance
export const deleteAttendance = async (docRef: string, uid: string): Promise<Message> => {
  const barcodeRef = doc(firestore, "attendance", docRef);
  const userAttandanceRef = doc(barcodeRef, "students", uid);
  return await deleteDoc(userAttandanceRef)
    .then(() => {
      return new Message(2, "Deleted Attendance")
    })
    .catch(() => {
      return new Message(0, "Something went wrong");
    })
}
// --------------------------------------------------------------------------------------------
